### ISSUE TITLE
Performance change

### ISSUE THREAD

**Issue by IvanUkhov** [stainless-steel/libblas-sys#4]
I’ve tried measuring the change in performance using [blas][0], and here is what I’ve found.

[Before][1] switching to the new version of `libblas-sys`:

```
test benches::dgemv_few_large  ... bench:   1638617 ns/iter (+/- 29219)
test benches::dgemv_many_small ... bench:   8130998 ns/iter (+/- 123919)
```

[After][2] switching to the new version of `libblas-sys`:

```
test benches::dgemv_few_large  ... bench:   1290354 ns/iter (+/- 71548)
test benches::dgemv_many_small ... bench: 154278315 ns/iter (+/- 2362811)
```

The slowdown for the latter is about 120 times.

[0]: https://github.com/stainless-steel/blas

[1]: https://github.com/stainless-steel/blas/tree/4bbb8bf34607fc07e47b61d25856e67c2e47848f

[2]: https://github.com/stainless-steel/blas/tree/4101d48d7b0225a4230d9f59e56c323f0310bc0e

**Comment by cmr** [comment]
Interesting. Taking a look...

**Comment by cmr** [comment]
Is that with the OpenBLAS or Netlib provider?

**Comment by IvanUkhov** [comment]
The default one, OpenBLAS.

**Comment by IvanUkhov** [comment]
`netlib-blas-provide` is not working at the moment due to a number of [issues](https://github.com/cmr/netlib-blas-provider/pulls).

**Comment by cmr** [comment]
I see:

```
test benches::dgemv_few_large  ... bench:   1434108 ns/iter (+/- 234800)
test benches::dgemv_many_small ... bench:   9596510 ns/iter (+/- 113869)
```

(netlib) versus (openblas):

```
test benches::dgemv_few_large  ... bench:    651278 ns/iter (+/- 719457)
test benches::dgemv_many_small ... bench:   4437524 ns/iter (+/- 527017)
```

That is, OpenBLAS is 2.201x faster than the reference implementation for the first, and 2.162x faster for the second. I suspect it might be a CPU model issue, but the OpenBLAS is also paying for copies into/out of each function, as I understand it, due to its support of multithreading. (I gleaned some of this info from https://github.com/xianyi/OpenBLAS/issues/103)
